- name: create ext volume for data
  file: state=directory path={{ ext_mysql_data_volume }}

- name: create ext volume for tmp
  file: state=directory path={{ ext_mysql_tmp_volume }} mode=1777

- name: create ext volume for /var/run
  file: state=directory path={{ ext_mysql_varrun_volume }} mode=1777

- name: start a Docker container
  docker_container:
    name: mysql
    image: mysql:{{ docker_mysql_tag }}
    state: started
    recreate: yes
    restart_policy: always
    read_only: yes
    exposed_ports:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - "{{ ext_mysql_data_volume }}:/var/lib/mysql"
      - "{{ ext_mysql_tmp_volume }}:/tmp"
      - "{{ ext_mysql_varrun_volume }}:/run/mysqld"
      - "/tmp/prueba:/prueba"
    env:
      MYSQL_ROOT_PASSWORD: "{{ docker_mysql_root_password }}"
      MYSQL_DATABASE: "{{ docker_mysql_database }}"
      MYSQL_USER: "{{ docker_mysql_user }}"
      MYSQL_PASSWORD: "{{ docker_mysql_password }}"

# - name: "Setup database"
#   mysql_db: 
#     state: import 
#     name: mysql 
#     target: /tmp/database.sql
#   args:
#     login_user: mysql
#     login_password: "1234567"
#   register: mysql

- name: wait for mysql container
  retries: 100
  delay: 10
  # shell: docker exec -it  mysql sh -c 'mysql --user=mysql --password=1234567 -e "SHOW DATABASES;"' > /tmp/prueba2.txt
  # shell: docker exec -it  mysql sh -c 'mysql --user=mysql -p mysql --password=1234567 -e "SET FOREIGN_KEY_CHECKS = 0;" < /prueba/cuadro.sql'
  shell: docker exec -it  mysql sh -c 'mysql --user=mysql -p mysql --password=1234567 -e "SET FOREIGN_KEY_CHECKS = 0;"'
  register: mysql
  until: mysql.rc == 0